//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dominio
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ML_TesisEntities : DbContext
    {
        public ML_TesisEntities()
            : base("name=ML_TesisEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<PortServices> PortServices { get; set; }
        public virtual DbSet<RangoIp> RangoIp { get; set; }
        public virtual DbSet<IpsMaliciosas> IpsMaliciosas { get; set; }
    }
}
